name: Publish to NuGet

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
          
      - name: Pack
        run: dotnet pack --configuration Release -p:Version=${GITHUB_REF#refs/tags/v}
        
      - name: Publish
        run: |
          PACKAGE_PATH=$(ls bin/Release/*.nupkg)
          dotnet nuget push $PACKAGE_PATH \
            --api-key ${{ secrets.NUGET_API_KEY }} \
            --source https://api.nuget.org/v3/index.json \
            --skip-duplicate
